### ISSUE TITLE
[Bug] Cannot mark email as spam

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3046]
0.12.1 tested on Android, Firefox, Safari, Opera; mail.stg.lin-saas.com

1. Select an email 
2. Click Mark as spam
3. Nothing happens 

Expectation: email is moved to Spam and is marked as spam

https://github.com/user-attachments/assets/032e4600-d27e-4caf-8a68-e0a92555e004

**Comment by chibenwa** [comment]
https://github.com/user-attachments/assets/eb413a1e-652d-4679-8ca0-90cbcf71d987


Frontend bug:

 - nothing happens when I click the mark as spam button
 - works great when I click the "move" button

**Comment by hoangdat** [comment]
hi @chibenwa , it is conflict in `Spam` role. please upgrade backend which include "junk" role fixed

**Comment by chibenwa** [comment]
Well ideally front should support both to ease the migration ^^

**Comment by chibenwa** [comment]
Fixed by deploying backend 0.10.2

**Comment by hoangdat** [comment]
agree. Will apply for both `roles`

**Comment by chibenwa** [comment]
https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/122

**Comment by chibenwa** [comment]
@tprudentova fixed on staging

**Comment by dab246** [comment]
Fixed at #3049

**Comment by tprudentova** [comment]
https://github.com/user-attachments/assets/bab09159-43d9-4d26-8aa2-1a00da0a3d14

Tested on tmail.linagora.com, the issue is still there (it's fixed on staging though)

**Comment by hoangdat** [comment]
this is old version (v0.11.4) is less than staging version (0.12.0). Wait for release.
