### ISSUE TITLE
Blue bar: use 24h format to !

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#4153]
<img width="1508" height="635" alt="Image" src="https://github.com/user-attachments/assets/c8f27afb-0fd6-4af9-acce-fbd5d69ebde1" />

**Comment by dab246** [comment]
IMO, It has been fixed with this issue #4146

**Comment by poupotte** [comment]
@hoangdat : I don't access to blue bar on staging environment :/

<img width="1680" height="941" alt="Image" src="https://github.com/user-attachments/assets/be577131-7252-42d4-85ef-23a0127bedc6" />

**Comment by chibenwa** [comment]
Yes this is solved

**Comment by chibenwa** [comment]
> I don't access to blue bar on staging environment :/

https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/259

That's a configuration issue

**Comment by poupotte** [comment]
Hmm... I still don't have the blue bar; do I need to do something special on my end?

**Comment by chibenwa** [comment]
No just wait next release ;-)

Or ask an ops to tag and deploy latest version of the helm chart.

**Comment by chibenwa** [comment]
And you won't get it on old mails

**Comment by poupotte** [comment]
I tested on canary and I still see the time with 12h format but your sentence benoit 'And you won't get it on old mails', makes me think it might still be related to the release back?

<img width="1397" height="299" alt="Image" src="https://github.com/user-attachments/assets/17679922-46a4-4062-ac8d-103fee70aeb7" />

**Comment by chibenwa** [comment]
No **blue bar will not be shown on old mails**

But blue bar format is unrelated

If we see discrepency between date formats then it's an unsolved bug !

**Comment by hoangdat** [comment]
now it was aligned with 12h format: am, pm. 

what is your expectation? @poupotte

**Comment by poupotte** [comment]
<img width="1461" height="736" alt="Image" src="https://github.com/user-attachments/assets/3e5b3f48-dfd3-4bb6-a413-7796f69bf710" />

**Comment by chibenwa** [comment]
Mail body is irrelevant, it's another story and it would need to have date formatting as a plateforme setting.

**Comment by poupotte** [comment]
Oh ok, so I'll create this second task. Is it on the back-end side ?

**Comment by chibenwa** [comment]
github.com/linagora/twake-calendar-side-service
